### ISSUE TITLE
promdump: create tarball/bundle when performing dump.

### ISSUE THREAD

**Issue by eugeneckim** [yugabyte/yb-tools#113]
this is a request per discussion with @ionthegeek where customers run promdump and then tar up/compress exports in different ways.  this is a request to have promdump create the bundle in a consistent manner.  this can aid downstream automation efforts.

**Comment by ionthegeek** [comment]
Implemented via https://github.com/yugabyte/prometheus-remote-backfill/pull/15. Closing.
