### ISSUE TITLE
tablet-report-parser create view for bootstrapping progress

### ISSUE THREAD

**Issue by eugeneckim** [yugabyte/yb-tools#152]
Related discussion where this query can be useful to see how many bootstraps are running:

```SELECT
    count(t.tablet_uuid) AS total_tablets,
    substr(c.ip, 1, 50) AS host
FROM
    cluster c,
    tablet t
WHERE
    c.uuid = t.node_uuid
    AND t.status = 'TABLET_DATA_COPYING'
GROUP BY 2

UNION ALL

SELECT
    count(t.tablet_uuid) AS total_tablets,
    'Total' AS host
FROM
    cluster c,
    tablet t
WHERE
    c.uuid = t.node_uuid
    AND t.status = 'TABLET_DATA_COPYING';```

Can we get this, or similar, in the form of a view?

**Comment by eugeneckim** [comment]
@pgyogesh -> Per our discussion.

**Comment by na6vj** [comment]
Please approve pull request
https://github.com/yugabyte/yb-tools/pull/153

that satisfies this request.
The requested "copying" counts have be incorporated into the existing "tablets_per_node" view.
Both moses.pl and tablet_report_parser.pl have this feature now.
