### ISSUE TITLE
Add timestamp to Yugatool reports

### ISSUE THREAD

**Issue by ionthegeek** [yugabyte/yb-tools#43]

**Comment by na6vj** [comment]
I have built yugatool with this feature.
The test-binary is available on lincoln: ~/vinay/yugatool

The output looks like this:
` bin/yugatool --master-addresses=$MASTERS   cluster_info  --skiphostverification    | head -15
[ ReportInfo ]
              DATE                 HOSTNAME                 TOOLS_VERSION                        TOOLS_BUILD
 2022-12-13T05:10:03.266346966Z   kachand-yb   d9fcda2039ce3aae2e92f9731b084db9f15965fd   2022-12-12T21:09:05-08:00

[ Cluster ]
             CLUSTER_UUID               LIVE_REPLICAS                      ZONES                      VERSION
 d89e6b62-8afb-4310-8e13-db7bf482afa6   3               ["us-west1-a" "us-east1-b" "us-central1-a"]   23
...
`

Please test.

**Comment by ionthegeek** [comment]
Output looks good. Do you have this checked into a branch somewhere for a quick code review?

**Comment by na6vj** [comment]
Output date is now better formatted:
`[ ReportInfo ]
          DATE              HOSTNAME                 TOOLS_VERSION                        TOOLS_BUILD
 2022-12-14T04:23:10 UTC   kachand-yb   3241615a8e28be50941705e316073e71e8af2593   2022-12-13T19:30:36-08:00
`

Checked in to add-report-header branch.

Also updated the output of --version to include build date.

**Comment by tvesely** [comment]
Resolved by #45
