### ISSUE TITLE
tablet-report-parser.pl multi-source awareness

### ISSUE THREAD

**Issue by eugeneckim** [yugabyte/yb-tools#48]
- Based on the overwhelming usefulness of `tablet-report-parser.pl` the following are some requests captured recently:

  - Ideally if we had one tool versus additional tools like `entity_parser.pl` the tool could process any list of files and deliver one consolidated database afterwards.

    For example:

    `./tablet-report-parser.pl <tablet_report_file> <dump_entities> <tablet_info> | sqlite3 blah.sqlite`

    Should yield tables which have information processed from these various sources.

**Comment by na6vj** [comment]
Commit e637601f3c31727aabe9d45f7c028565c512a17e on the vanand-dev branch implements this request.

It can take a list of files - tablet-report , entity-info, and tablet-info , process them all into a single DB.
Note - file naming is significant. Entity files must have "entities" in the name.
Tablet_info files must be of the form "<tablet-uuid>.txt"
