### ISSUE TITLE
tablet-report-parser.pl handling of existing .sqlite file

### ISSUE THREAD

**Issue by eugeneckim** [yugabyte/yb-tools#49]
If running `tablet-report-parser.pl` and you run it to an existing `.sqlite` file errors will be returned of unique-ness of IDs, etc. and can cause confusion for users.  Some thoughts from a working session today:

- Can error checking be added to prevent overwrite and stop?  My assumption is that we wouldn't want to overwrite the `.sqlite` file.
- Or can the utility be simplified such that the parser can generate the sqlite file?  This way the utility doesn't have to be piped into sqlite3 at runtime, simplifying the use of the utility.

**Comment by na6vj** [comment]
Version 0.28+ includes these fixes.

* piping to sqlite is no longer necessary. The program will run sqlite internally. Just need the tablet report as input.
* When run in the manner above, an existing .sqlite file will be auto-renamed ONCE, with a warning, and a new sqlite file created.
   A second run attempt (with now 2 .sqlite files) will error-terminate, and require manual cleanup.
