### ISSUE TITLE
Promdump - Add "job_name=platform"

### ISSUE THREAD

**Issue by eugeneckim** [yugabyte/yb-tools#91]
Request to grab platform metrics by default as the `ybp_.*` metrics are very helpful and supplement the core metrics nicely.

**Comment by eugeneckim** [comment]
Unable to open an issue directly in https://github.com/yugabyte/prometheus-remote-backfill

But this is being haneled via

https://github.com/yugabyte/prometheus-remote-backfill/pull/9

**Comment by ionthegeek** [comment]
Fixed by https://github.com/yugabyte/prometheus-remote-backfill/pull/9
